### ISSUE TITLE
Custom Emojis looks very odd. 

### ISSUE THREAD

**Issue by dinosw** [Nordskog/SwiftKeyExi#45] opened 2018-08-13 06:54 UTC
My custom Emojis looks odd in the tab, but fine when used. 
Also, one of the tabs you have added, have somehow had a name change to the shrug emoji, even when I am unable to change it myself =S 

![Screenshot](https://i.imgur.com/VdE6iWk.png)

**Comment by Nordskog** [comment] 2018-08-13 19:39
That is... strange. 
Unfortunately something has gone wrong with your screenshot, it does not appear to point to a valid image file.

**Comment by dinosw** [comment] 2018-08-13 21:00
Here's a new screenshot: 
![Screenshot](https://imgur.com/a/S22gjRg)

**Comment by dinosw** [comment] 2018-08-13 21:04
Sorry, I had in my haste copied the link to the imgur page, rather than the image url itself.

**Comment by Nordskog** [comment] 2018-08-13 21:16
Oh, I see what's going on.
The column-width defaults to 1-emoji unit (e.g. the width of a single standard emoji), forcing the emoji to be displayed vertically like that. You can configure the width of any given panel by opening the menu and select "column-width", which will present a widget you can scroll to adjust it.

The recent-emoji panel is an exception, as it will necessarily have to accommodate emoji from panels with with different column widths. Auto-width is possible there only because it is limited to 30 or so items.

**Comment by dinosw** [comment] 2018-08-14 06:26
Thank you very much.
And true, the recently used list does indeed format the kaomoji correctly.
Speaking of the 「recently used」, it doesn't display recently used regular Emojis.

**Comment by Nordskog** [comment] 2018-08-16 04:45
"Regular" emojis?

There is a known issue that can sometimes cause recent emoji to be cleared.
I'm still not sure how it happens, and I'm not even sure I've been able to reproduce it, but I have eliminated the one potential cause of it in https://github.com/Nordskog/SwiftKeyExi/commit/6b24716672be0dd0d0163c60435fe2a00bce0830, so that should hopefully be fixed in the next release.

Currently waiting for the translation team.

**Comment by Nordskog** [comment] 2018-08-21 03:35
Dev branched merged with master and 1.6.0 released targeting Swiftkey 7.1.2.21, with this issue fixed.
Note that there were some backwards-compatibility breaking changes, so you should stick with the previous release if you are not using Swiftkey Beta.

**Closed** 2018-08-27 18:18 UTC
